#! /bin/sh
#
#	handle the tclhttpd web server
#
set -x
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/var/www/H/Sandbox.tcl
NAME=H
DESC="H Web Server"
TCLSH=/usr/bin/tclsh8.6
STARTER="daemon"

#test -x $DAEMON || exit 0

# Include tclhttpd defaults if available
if [ -f /etc/default/H ] ; then
	. /etc/default/H
fi

set -e

case "$1" in
  start)
	echo -n "Starting $DESC with $STARTER: "
	if [ $STARTER = "daemon" ]; then
	    /usr/bin/daemon --name=H \
		--chdir=/var/www/H \
		--pidfiles /var/www/H/pid \
		--dbglog=/var/log/H/H.daemon \
		--user=www-data.www-data --umask=005 \
		--respawn --inherit --core \
		--errlog=/var/log/H/H.err --output=/var/log/H/H.out \
		$TCLSH $DAEMON $DAEMON_OPTS
	else
	    start-stop-daemon --start --quiet --background \
		--chuid www-data:www-data \
		--pidfiles /var/www/H/pid \
		--exec $TCLSH -- $DAEMON $DAEMON_OPTS
	fi
	echo "$NAME."
	;;

  stop)
	echo -n "Stopping $DESC: "
	if [ $STARTER = "daemon" ]; then
	    /usr/bin/daemon --user www-data.www-data --name=H --stop
	else
	    start-stop-daemon --stop --quiet --pidfile /var/run/$NAME.pid \
		--exec $TCLSH
	fi
	echo "$NAME."
	;;

  restart|force-reload)
	#
	#	If the "reload" option is implemented, move the "force-reload"
	#	option to the "reload" entry above. If not, "force-reload" is
	#	just the same as "restart".
	#
	echo -n "Restarting $DESC: "
	if [ $STARTER = "daemon" ]; then
	    /usr/bin/daemon --user www-data.www-data --name=H --restart
	else
	    start-stop-daemon --stop --quiet --pidfile \
		/var/run/$NAME.pid --exec $DAEMON
	    sleep 1
	    start-stop-daemon --start --quiet --pidfile \
		/var/run/$NAME.pid --exec $DAEMON -- $DAEMON_OPTS
	fi

	echo "$NAME."
	;;

  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart}" >&2
	exit 1
	;;
esac

exit 0
